### ISSUE TITLE
create "Unit" pages for each repository/Institution-owner that list all collections associated with a unit

### ISSUE THREAD

**Issue by aturner** [ucldc/avram#70]

**Comment by tingletech** [comment]
what is the repository view?

**Comment by tingletech** [comment]
| "Unit" view
|
| Sent from my iPhone

Can I please have a URL?  Is this the public side; or on the admin site?

Are you asking for the links on this page to be clickable? https://registry.cdlib.org/repositories/

and then when you click on that link; you get to all the collections in that "Owning Institution"?

**Comment by sherribee** [comment]
I actually don't know what Adrian intended but your interpretation sounds reasonable. There's a pivotal with some wireframes he sketched out but I don't know how it relates to the github issues.


On Mar 15, 2015, at 9:37 AM, "Brian Tingle" <notifications@github.com<mailto:notifications@github.com>> wrote:


| "Unit" view
|
| Sent from my iPhone

Can I please have a URL? Is this the public side; or on the admin site?

Are you asking for the links on this page to be clickable? https://registry.cdlib.org/repositories/

and then when you click on that link; you get to all the collections in that "Owning Institution"?

**Comment by tingletech** [comment]
it is not in this pivotal-with-wireframes https://www.pivotaltracker.com/story/show/85661556  I was just in here because I noticed https://github.com/ucldc/avram/issues/72 when I was checking that registry started okay after patching for GHOST
